
all:
	-cd test && make all
	-cd ktty && make all
	-cd usertest && make all
	-cd bar && make all
	-cd gcat && make all
	-cd ql && make all
	-cd edit && make all
clean:
	-cd test && make clean
	-cd ktty && make clean
	-cd usertest && make clean
	-cd bar && make clean
	-cd gcat && make clean
	-cd ql && make clean
	-cd edit && make clean